name: Test

on: [ push ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PIPENV_IGNORE_VIRTUALENVS: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: x64
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -q pipenv codecov flake8
          pipenv sync --dev
      - name: Rodar flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names 
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide 
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Rodar tests
        run: |
          pipenv run pytest libpythonpro --cov=libpythonpro
      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pipenv run codecov
