name: Test

on: [ push ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: x64
      - name: Instalar dependências
        run: |
          pip install -r requirements-dev.txt codecov
      - name: Rodar flake8
        uses: py-actions/flake8@v1

      - name: Rodar tests
        run: |
          pytest --cov=libpythonpro
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
      
